{{- if .Values.rfsimGnb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: gnb-nfapi-pnf-rfsim-svc
  labels:
    app: gnb-nfapi-pnf-rfsim
spec:
  type: ClusterIP
  selector:
    app: gnb-nfapi-pnf-rfsim
  ports:
    - name: n3
      port: 2152
      targetPort: 2152
      protocol: UDP
    - name: n2
      port: 36412
      targetPort: 36412
      protocol: SCTP
    - name: nfapi-p5
      port: 50000
      targetPort: 50000
      protocol: SCTP
    - name: nfapi-p7
      port: 50010
      targetPort: 50010
      protocol: UDP
{{- end }}
