{{- if .Values.nfapiGnb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: gnb-nfapi-vnf-svc
  labels:
    app: gnb-nfapi-vnf
spec:
  type: ClusterIP
  selector:
    app: gnb-nfapi-vnf
  ports:
  - name: nfapi-p5
    port: 50001
    targetPort: 50001
    protocol: SCTP
  - name: nfapi-p7
    port: 50011
    targetPort: 50011
    protocol: UDP
{{- end }}
