{{- if .Values.gnbNfapiVnf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gnb-nfapi-vnf-configmap
data:
  du.conf: |
{{- range $line := (splitList "\n" (include "nfapi-gnb.duconf" .)) }}
    {{ $line }}
{{- end }}
{{- end }}

