{{- if and .Values.gnbNfapiVnf.enabled .Values.gnbNfapiVnf.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gnbNfapiVnf.serviceAccount.name }}
---
{{- end }}
{{- if and .Values.gnbNfapiPnfRfsim.enabled .Values.gnbNfapiPnfRfsim.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gnbNfapiPnfRfsim.serviceAccount.name }}
---
{{- end }}
{{- if and .Values.nrUe.enabled .Values.nrUe.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nrUe.serviceAccount.name }}
{{- end }}

