{{- if and .Values.nfapiGnb.enabled .Values.nfapiGnb.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nfapiGnb.serviceAccount.name }}
---
{{- end }}
{{- if and .Values.rfsimGnb.enabled .Values.rfsimGnb.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rfsimGnb.serviceAccount.name }}
---
{{- end }}
{{- if and .Values.nrUe.enabled .Values.nrUe.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nrUe.serviceAccount.name }}
{{- end }}

